//! Private, per-user drafts.
//!
//! Drafts are never written into the shared workspace. When persistent drafts
//! are enabled they are saved under the user's own local app-data folder
//! (`%LOCALAPPDATA%\Cairn\drafts` on Windows, which only that user can read),
//! including staged pictures that have not been published yet. When disabled
//! or unavailable, drafts live only in this running session.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::sync::Mutex;

use serde::{Deserialize, Serialize};

use crate::error::{CairnError, Result};
use crate::fsutil::{read_optional, sha256_hex, write_atomic};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct StagedImage {
    /// Final file name inside the article's `.assets` folder.
    pub name: String,
    /// Workspace-relative path the picture will be published to.
    pub target_rel: String,
    pub mime: String,
    pub size: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Draft {
    pub article: String,
    pub instance_id: String,
    /// Hash of the published article when editing began (`None` for a new page).
    pub base_hash: Option<String>,
    pub content: String,
    /// Unix seconds.
    pub updated_at: u64,
    pub is_new: bool,
    pub staged: Vec<StagedImage>,
}

#[derive(Debug, Clone, Serialize)]
pub struct SaveOutcome {
    /// True if the draft reached disk; false if it is only held in memory.
    pub persisted: bool,
    /// Plain-language reason persistence failed, if it did.
    pub error: Option<String>,
}

#[derive(Default)]
struct MemEntry {
    draft: Option<Draft>,
    images: HashMap<String, Vec<u8>>,
}

pub struct DraftStore {
    dir: Option<PathBuf>,
    mem: Mutex<HashMap<String, MemEntry>>,
}

fn article_key(article: &str) -> String {
    sha256_hex(article.to_lowercase().as_bytes())[..32].to_string()
}

fn mem_key(instance_id: &str, article: &str) -> String {
    format!("{instance_id}/{}", article_key(article))
}

/// Staged picture names are generated by Cairn; anything else is refused.
fn validate_image_name(name: &str) -> Result<()> {
    let ok = !name.is_empty()
        && name.len() <= 120
        && !name.starts_with('.')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'));
    if ok {
        Ok(())
    } else {
        Err(CairnError::PathRejected("Invalid picture name.".into()))
    }
}

impl DraftStore {
    /// `dir = None` disables persistent drafts. If the folder can't be
    /// created, drafts fall back to session-only.
    pub fn new(dir: Option<PathBuf>) -> DraftStore {
        let dir = dir.filter(|d| fs::create_dir_all(d).is_ok());
        DraftStore {
            dir,
            mem: Mutex::new(HashMap::new()),
        }
    }

    /// Default private location: `<local app data>/Cairn/drafts`.
    pub fn default_dir() -> Option<PathBuf> {
        dirs::data_local_dir().map(|d| d.join("Cairn").join("drafts"))
    }

    pub fn is_persistent(&self) -> bool {
        self.dir.is_some()
    }

    fn disk_dir(&self, instance_id: &str, article: &str) -> Option<PathBuf> {
        let base = self.dir.as_ref()?;
        // Instance ids are UUIDs from a validated marker; keep only safe chars.
        let inst: String = instance_id
            .chars()
            .filter(|c| c.is_ascii_alphanumeric() || *c == '-')
            .collect();
        if inst.is_empty() {
            return None;
        }
        Some(base.join(inst).join(article_key(article)))
    }

    pub fn save(&self, draft: &Draft) -> SaveOutcome {
        {
            let mut mem = self.mem.lock().expect("draft lock");
            mem.entry(mem_key(&draft.instance_id, &draft.article))
                .or_default()
                .draft = Some(draft.clone());
        }
        let Some(dir) = self.disk_dir(&draft.instance_id, &draft.article) else {
            return SaveOutcome {
                persisted: false,
                error: None,
            };
        };
        let bytes = serde_json::to_vec_pretty(draft).expect("draft serializes");
        match fs::create_dir_all(&dir).and_then(|_| write_atomic(&dir.join("draft.json"), &bytes)) {
            Ok(()) => SaveOutcome {
                persisted: true,
                error: None,
            },
            Err(err) => SaveOutcome {
                persisted: false,
                error: Some(format!(
                    "Your unsaved copy could not be saved to this computer ({err}). It is kept \
                     only while Cairn stays open."
                )),
            },
        }
    }

    pub fn load(&self, instance_id: &str, article: &str) -> Option<Draft> {
        let cached = self
            .mem
            .lock()
            .expect("draft lock")
            .get(&mem_key(instance_id, article))
            .and_then(|e| e.draft.clone());
        if cached.is_some() {
            return cached;
        }
        let dir = self.disk_dir(instance_id, article)?;
        let bytes = read_optional(&dir.join("draft.json")).ok()??;
        let draft: Draft = serde_json::from_slice(&bytes).ok()?;
        (draft.article.eq_ignore_ascii_case(article) && draft.instance_id == instance_id)
            .then_some(draft)
    }

    /// Every draft for one documentation folder: those saved on this
    /// computer and those held only in memory (the in-memory copy wins).
    pub fn list(&self, instance_id: &str) -> Vec<Draft> {
        let mut by_article: HashMap<String, Draft> = HashMap::new();
        if let Some(base) = self.dir.as_ref() {
            let inst: String = instance_id
                .chars()
                .filter(|c| c.is_ascii_alphanumeric() || *c == '-')
                .collect();
            if let Ok(entries) = fs::read_dir(base.join(&inst)) {
                for entry in entries.flatten() {
                    let Ok(Some(bytes)) = read_optional(&entry.path().join("draft.json")) else {
                        continue;
                    };
                    if let Ok(draft) = serde_json::from_slice::<Draft>(&bytes)
                        && draft.instance_id == instance_id
                    {
                        by_article.insert(draft.article.to_lowercase(), draft);
                    }
                }
            }
        }
        let prefix = format!("{instance_id}/");
        for (key, entry) in self.mem.lock().expect("draft lock").iter() {
            if let (true, Some(draft)) = (key.starts_with(&prefix), entry.draft.as_ref()) {
                by_article.insert(draft.article.to_lowercase(), draft.clone());
            }
        }
        by_article.into_values().collect()
    }

    /// Stage a picture for a draft. The draft must already exist.
    pub fn add_image(
        &self,
        instance_id: &str,
        article: &str,
        image: StagedImage,
        bytes: Vec<u8>,
    ) -> Result<SaveOutcome> {
        validate_image_name(&image.name)?;
        let mut draft = self.load(instance_id, article).ok_or_else(|| {
            CairnError::NotFound("Start editing the page before adding pictures.".into())
        })?;
        let mut disk_error = None;
        if let Some(dir) = self.disk_dir(instance_id, article) {
            let staged = dir.join("staged");
            if let Err(err) = fs::create_dir_all(&staged)
                .and_then(|_| write_atomic(&staged.join(&image.name), &bytes))
            {
                disk_error = Some(format!(
                    "The picture could not be saved to this computer ({err}). It is kept only \
                     while Cairn stays open."
                ));
            }
        }
        self.mem
            .lock()
            .expect("draft lock")
            .entry(mem_key(instance_id, article))
            .or_default()
            .images
            .insert(image.name.clone(), bytes);
        if !draft.staged.iter().any(|s| s.name == image.name) {
            draft.staged.push(image);
        }
        let outcome = self.save(&draft);
        Ok(match disk_error {
            Some(e) => SaveOutcome {
                persisted: false,
                error: Some(e),
            },
            None => outcome,
        })
    }

    pub fn image_bytes(&self, instance_id: &str, article: &str, name: &str) -> Option<Vec<u8>> {
        validate_image_name(name).ok()?;
        let cached = self
            .mem
            .lock()
            .expect("draft lock")
            .get(&mem_key(instance_id, article))
            .and_then(|e| e.images.get(name).cloned());
        if cached.is_some() {
            return cached;
        }
        let dir = self.disk_dir(instance_id, article)?;
        read_optional(&dir.join("staged").join(name)).ok()?
    }

    /// Remove a draft and its staged pictures (after a verified publish or an
    /// explicit discard).
    pub fn discard(&self, instance_id: &str, article: &str) -> Result<()> {
        self.mem
            .lock()
            .expect("draft lock")
            .remove(&mem_key(instance_id, article));
        if let Some(dir) = self.disk_dir(instance_id, article)
            && dir.exists()
        {
            fs::remove_dir_all(&dir)?;
        }
        Ok(())
    }

    /// Forget in-memory state (simulates an app restart in tests).
    pub fn clear_memory(&self) {
        self.mem.lock().expect("draft lock").clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_unsafe_image_names() {
        assert!(validate_image_name("shot-a1b2c3d4.png").is_ok());
        assert!(validate_image_name("../x.png").is_err());
        assert!(validate_image_name("a/b.png").is_err());
    }
}
